# Generated by Django 5.0.1 on 2026-06-16 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawSessionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=50)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('programme', models.CharField(blank=True, max_length=200)),
                ('facilitator', models.CharField(blank=True, max_length=200)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('attendees', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('source_file', models.CharField(max_length=500)),
                ('import_timestamp', models.DateTimeField(auto_now_add=True)),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['-import_timestamp'],
                'indexes': [models.Index(fields=['session_code', 'source_file'], name='ingestion_r_session_2dce39_idx'), models.Index(fields=['import_timestamp'], name='ingestion_r_import__d57034_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsolidatedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('programme', models.CharField(blank=True, max_length=200)),
                ('facilitator', models.CharField(blank=True, max_length=200)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('attendees', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_sources', models.ManyToManyField(related_name='consolidated_sessions', to='ingestion.rawsessionrow')),
            ],
            options={
                'indexes': [models.Index(fields=['organisation'], name='ingestion_c_organis_c8b01c_idx'), models.Index(fields=['programme'], name='ingestion_c_program_e96df4_idx'), models.Index(fields=['session_date'], name='ingestion_c_session_23989f_idx'), models.Index(fields=['organisation', 'programme'], name='ingestion_c_organis_98346c_idx'), models.Index(fields=['session_date', 'organisation'], name='ingestion_c_session_df9627_idx')],
            },
        ),
    ]
